ueransim:
  docker:
    network:
      macvlan:
        name: ueransimnet

  servers:
    "0":
      gnb: "config/custom-gnb.yaml"
      ue: "config/custom-ue.yaml"
core:
  amf:
    ip: "172.16.248.6"
