---

- name: install ueransim/router
  import_tasks: roles/router/tasks/install.yml
  tags: install

- name: uninstall ueransim/router
  import_tasks: roles/router/tasks/uninstall.yml
  tags: uninstall
