---

- name: copy gnb config file to ueransim host
  copy:
    src: "{{ ROOT_DIR }}/config/custom-gnb.yaml"
    dest: UERANSIM/config/custom-gnb.yaml
  tags:
    - ueransim
- name: copy ue config file to ueransim host
  copy:
    src: "{{ ROOT_DIR }}/config/custom-ue.yaml"
    dest: UERANSIM/config/custom-ue.yaml
  tags:
    - ueransim
- name: Run gNB
  shell: nohup ./nr-gnb -c ../config/custom-gnb.yaml > /dev/null 2>&1 &
  async: 30
  poll: 0
  args:
    chdir: UERANSIM/build
  register: gnb_output
  tags:
    - ueransim
- debug:
    var: gnb_output
- name: Run UE
  shell: nohup ./nr-ue -c ../config/custom-ue.yaml > /dev/null 2>&1 &
  args:
    chdir: UERANSIM/build
  tags:
    - ueransim

