---
- name: force stop gNB
  command: pkill -9 -f nr-gnb
  ignore_errors: yes
  become: true
  when: inventory_hostname in groups['ueransim_nodes']

- name: force stop UE
  command: pkill -9 -f nr-ue
  ignore_errors: yes
  become: true
  when: inventory_hostname in groups['ueransim_nodes']

- name: remove UERANSIM
  file:
    path: ueransim_onramp
    state: absent
  ignore_errors: yes
  become: true  
  when: inventory_hostname in groups['ueransim_nodes']
  
- set_fact:
    subnet: "{{ core.upf.access_subnet | regex_replace('[0-9]+/24', '0/24') }}"
  when: inventory_hostname in groups['ueransim_nodes']

- name: remove static route for upf traffic on ueransim node
  shell: |
    ip route del {{ subnet }} via {{ core.amf.ip }}
  when: (inventory_hostname in groups['ueransim_nodes']) and (inventory_hostname not in groups['master_nodes'])
  become: true
  ignore_errors: yes
